networks:
  libraryplatform:
    driver: bridge
services:
  db:
    hostname: libraryplatform-db
    networks:
      - libraryplatform
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_DB: libraryplatform
  admin:
    image: adminer
    networks:
      - libraryplatform
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080