-- liquibase formatted sql

-- changeset d4rck:1733127293604-2
CREATE TABLE ratings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    book_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_ratings PRIMARY KEY (id)
);

-- changeset d4rck:1733127293604-3
ALTER TABLE ratings
    ADD CONSTRAINT FK_RATINGS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

-- changeset d4rck:1733127293604-4
ALTER TABLE ratings
    ADD CONSTRAINT FK_RATINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset d4rck:1733127293604-1
ALTER TABLE books
    ALTER COLUMN year SET NOT NULL;

