-- liquibase formatted sql

-- changeset d4rck:1727330189403-1
CREATE TABLE books
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255)                            NOT NULL,
    author         VARCHAR(255)                            NOT NULL,
    isbn           VARCHAR(255)                            NOT NULL,
    publisher      VARCHAR(255)                            NOT NULL,
    published_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

-- changeset d4rck:1727330189403-2
CREATE TABLE books_tags
(
    book_entity_id BIGINT NOT NULL,
    tags_id        BIGINT NOT NULL
);

-- changeset d4rck:1727330189403-3
CREATE TABLE borrowings
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT,
    item_id       BIGINT,
    borrow_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    return_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    returned_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_borrowings PRIMARY KEY (id)
);

-- changeset d4rck:1727330189403-4
CREATE TABLE inventory
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_id BIGINT,
    CONSTRAINT pk_inventory PRIMARY KEY (id)
);

-- changeset d4rck:1727330189403-5
CREATE TABLE tags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

-- changeset d4rck:1727330189403-6
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset d4rck:1727330189403-7
ALTER TABLE borrowings
    ADD CONSTRAINT FK_BORROWINGS_ON_ITEM FOREIGN KEY (item_id) REFERENCES inventory (id);

-- changeset d4rck:1727330189403-8
ALTER TABLE borrowings
    ADD CONSTRAINT FK_BORROWINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset d4rck:1727330189403-9
ALTER TABLE inventory
    ADD CONSTRAINT FK_INVENTORY_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

-- changeset d4rck:1727330189403-10
ALTER TABLE books_tags
    ADD CONSTRAINT fk_bootag_on_book_entity FOREIGN KEY (book_entity_id) REFERENCES books (id);

-- changeset d4rck:1727330189403-11
ALTER TABLE books_tags
    ADD CONSTRAINT fk_bootag_on_tag_entity FOREIGN KEY (tags_id) REFERENCES tags (id);

