-- liquibase formatted sql

-- changeset andrei:1731526138107-2
CREATE TABLE reservations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    item_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expired_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_reservations PRIMARY KEY (id)
);

-- changeset andrei:1731526138107-4
ALTER TABLE users
    ALTER COLUMN hashed_password SET NOT NULL;

-- changeset andrei:1731526138107-5
ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_ITEM FOREIGN KEY (item_id) REFERENCES inventory (id);

-- changeset andrei:1731526138107-6
ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset andrei:1731526138107-1
ALTER TABLE inventory
    ALTER COLUMN book_id SET NOT NULL;

