-- liquibase formatted sql

-- changeset andrei:1732722774956-1
CREATE TABLE stats
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stat_date          date                                    NOT NULL,
    daily_borrowings   BIGINT                                  NOT NULL,
    daily_returns      BIGINT                                  NOT NULL,
    daily_reservations BIGINT                                  NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);

